### PR TITLE
Update package lock to match 0.16.4 release

### PR DESCRIPTION
**Pull request by turboMaCk**
Update package-lock.json which is not aligned with package.json

### CODE REVIEW

**Comment by turboMaCk** [comment]
Windows build failed due to an HTTP error:

```

The following HTTP request failed:
    <https://package.elm-lang.org/all-packages>
Here is the error message I was able to extract:
    HttpExceptionRequest Request { host = "package.elm-lang.org" port = 443
    secure = True requestHeaders =
    [("User-Agent","elm/0.19.0"),("Accept-Encoding","gzip")] path =
    "/all-packages" queryString = "" method = "GET" proxy = Nothing rawBody =
    False redirectCount = 10 responseTimeout = ResponseTimeoutDefault
    requestVersion = HTTP/1.1 } (ConnectionFailure user error
    (Network.Socket.gai_strerror not supported: 11001))
```

**Comment by turboMaCk** [comment]
I think this mismatch might be the reason why the last version doesn't compile using node2nix. Though a new version of node2nix will have a workaround for this issue.

**Comment by stil4m** [comment]
@turboMaCk This I see that there is a version mismatch on the project version in the lock file, but there are additional changes in you PR (`optional`) which I think relate to node version 10. This package is still on version 8. I'll patch the `package-lock.json`, does that suffice for the Nix package?

**Comment by turboMaCk** [comment]
@stil4m I've tried to rerun this with `node v8.15.1` and `npm 6.4.1` and it even those versions are adding `optional` attribute. I see [v8 specified in nvmrc](https://github.com/stil4m/elm-analyse/blob/master/.nvmrc#L1) though [node2nix](https://github.com/svanderburg/node2nix) detected this package is using v6 probably based on the format of the lock file.

We don't care that much in nix as the newer version of node2nix has a workaround for situations like this (even though I'm yet to test it on this case). If you wish to fix it in another way feel free to close this PR but as far as I can tell this is the right format for node 8 and current state of master.

**Comment by turboMaCk** [comment]
thanks @stil4m btw I can confirm that latest version of node2nix has no issue with latest release https://github.com/NixOS/nixpkgs/pull/64486

**Comment by stil4m** [comment]
@turboMaCk Thanks. I've just restricted the nvmrc even more (to include a minor and a patch). This may be the difference I've seen on my machine and the PR you've created. 

Great to hear that there are no issues.

I'm not sure if it is possible, but could we add a CI check with `node2nix` to verify if the repository has a valid setup?

**Comment by turboMaCk** [comment]
@stil4m if you would like to have something like this I can try to investigate possible solution. The main concern though is about build times though. I'm not sure if it won't slow the ci too much which might be quite annoying for you and other contributors. In some sense it's the job of node2nix project to be compatible with npm and node. This PR was just chore I run into while debugging. I think the correct solution to any node2nix build error is likely bugfix in node2nix rather than in this or any other package. Think about it and let me know if you're still interested in having it in CI pipeline.

**Pull request merged**
