### PR TITLE
Use a checker to emit elm-format issues

### PR DESCRIPTION
**Pull request by gollerob**
Currently elm-format messages cannot be disabled in the `elm-analyse.json`.
Moving the `elm-format` message creation into a checker solves this issue without adding complexity.

### CODE REVIEW

**Comment by stil4m** [comment]
Thank. You structured the code as it has to be :). I kinda messed that part up.

Could you revert the changes on the JS code?
I want to keep the PRs as clean as possible. I'll build the JS before I'll release the next version.

**Comment by gollerob** [comment]
Sure, done.

**Comment by stil4m** [comment]
Merged. Thank you for your contribution!

**Comment by stil4m** [comment]
Just released 0.9.5

**Pull request merged**
