### PR TITLE
Issue #131: Add check for Nothing -> Nothing

### LINKED ISSUE #131: Check: Do not map Nothing to Nothing
Do not map a nothing to nothing with a case expression. Use `andThen` or `map` instead.

Example:

```
case x of 
    Nothing -> Nothing
    Just a -> Just (a + 1)
```

or

```
case x of
    Nothing -> Nothing
    Just a -> Dict.get "foo" a
```

### PR DESCRIPTION
**Pull request by adeschamps**
Fixes #131

### CODE REVIEW

**Comment by stil4m** [comment]
Nice! I add you to my list of personal heroes :). The implementation looks good!  Could you maybe also add the check to the docs (docs/Docs/MsgDoc.elm)?

**Comment by adeschamps** [comment]
I gave it a shot, but the dynamic `MsgExample` isn't working. I used the same code as my unit test, but it crashes with a `Nothing` in `getMessage`. Any pointers?

**Comment by stil4m** [comment]
Ok. No problem. I'll merge it and have a look at it. Thanks again for your contribution :)

**Comment by adeschamps** [comment]
Oh, I see what you did - my example wasn't written as a module. Thanks!

**Pull request merged**
